# Generated by Django 5.2.4 on 2025-07-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_productcategory_order_orderitem_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(to='shop.productcategory'),
        ),
    ]
